/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
        final int width = 600;
        final int height = 600;

        JFrame frame = new JFrame("Pinball");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.requestFocus();
        frame.setSize(width, height);
        frame.setVisible(true);
        MainWindow window = new MainWindow(600, 600);
        frame.add(window);
        frame.pack();
    }
}
